CI: Updates GH Actions (learnings from other projects) [fix]

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
+# SPDX-FileCopyrightText: 2021 - 2024 Robin Vobruba <hoijui.quaero@gmail.com>
 #
 # SPDX-License-Identifier: Unlicense
 
@@ -21,6 +21,11 @@
 
 name: release
 
+permissions:
+  # This is required by softprops/action-gh-release to create a release,
+  # see: <https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128>
+  contents: write
+
 on:
   push:
     tags:
@@ -38,6 +43,9 @@ jobs:
         uses: actions/checkout@v3
         if: env.OUR_VERSION == ''
         with:
+          # This makes sure we also get tags,
+          # so we get the correct version; see bug:
+          # https://github.com/actions/checkout/issues/701
           fetch-depth: 0
           submodules: true
 
@@ -72,7 +80,7 @@ jobs:
         build: [linux]
         include:
         - build: linux
-          os: ubuntu-20.04
+          os: ubuntu-latest
           rust: nightly
           target: x86_64-unknown-linux-musl
         # - build: linux-arm
@@ -113,7 +121,7 @@ jobs:
       run: scripts/env
 
     - name: Install packages (Ubuntu)
-      if: matrix.os == 'ubuntu-20.04'
+      if: matrix.os == 'ubuntu-latest'
       run: |
         scripts/install_deps_ubuntu
 
@@ -157,6 +165,34 @@ jobs:
     #       rustembedded/cross:arm-unknown-linux-gnueabihf \
     #       arm-linux-gnueabihf-strip \
     #       /target/arm-unknown-linux-gnueabihf/release/${{ env.BINARY }}
+
+    - name: Test Release Version (if binary)
+      shell: bash
+      run: |
+        export ENV_FILE="proj_build_envs.txt"
+        # This writes "BINARY=bla" to ENV_FILE
+        scripts/env
+        source "$ENV_FILE"
+        BIN="target/release/$BINARY"
+        if [ -f "$BIN" ]
+        then
+          VER_TOOL="$("$BIN" --version --quiet)"
+          VER_TAG="${GITHUB_REF#refs/*/}"
+          (
+            echo "VER_TOOL: $VER_TOOL"
+            echo "VER_TAG: $VER_TAG"
+          ) | tee /dev/stderr
+          if ! [ "$VER_TOOL" == "$VER_TAG" ]
+          then
+            >&2 echo "ERROR: Version reported by tool ('$VER_TOOL') should equal the release tag ('$VER_TAG')!"
+            exit 1
+          fi
+          if ! [[ $VER_TOOL =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
+          then
+            >&2 echo "ERROR: Version reported by tool ('$VER_TOOL') should be a semver compatible string, i.e. of the form: "'^[0-9]+\.[0-9]+\.[0-9]+$'
+            exit 2
+          fi
+        fi
 
     - name: Build archive
       shell: bash
